name: Delete a release

on:
  release:
    types: [ deleted ]

env:
  NPM_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release_deleted_job:
    runs-on: ubuntu-latest
    steps:
      - name: Delete a package
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          PACKAGE_VERSIONS_LIST=$(curl\
            -H "Authorization: Bearer ${{ env.NPM_TOKEN }}"\
            -H "Accept: application/vnd.github+json"\
            https://api.github.com/user/packages/npm/sem-release-experiments/versions)
          
          ID_TO_DELETE=$(echo "$PACKAGE_VERSIONS_LIST" | jq  --arg RELEASE_TAG $RELEASE_TAG '.[] | select(.name == $RELEASE_TAG) | .id')
          
          if [ -n "$ID_TO_DELETE" ]; then
            curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ env.NPM_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/user/packages/npm/sem-release-experiments/versions/$ID_TO_DELETE
          fi

